// decode_faad2_test.go
package aac

import (
	"os"
	"path/filepath"
	"testing"
)

// TestDecoder_Decode_FAAD2Reference compares output against FAAD2 reference data.
// This test requires:
// 1. AAC test files in testdata/
// 2. FAAD2 reference data generated by scripts/check_faad2
//
// To generate reference data:
//
//	./scripts/check_faad2 testdata/test.aac
//
// This creates /tmp/faad2_ref_test/ with per-frame PCM data.
func TestDecoder_Decode_FAAD2Reference(t *testing.T) {
	// Skip if test data not available
	testFile := "testdata/sine1k.aac"
	if _, err := os.Stat(testFile); os.IsNotExist(err) {
		t.Skip("sine1k.aac not found, skipping FAAD2 reference test")
	}

	// Load AAC file
	data, err := os.ReadFile(testFile)
	if err != nil {
		t.Fatalf("failed to read test file: %v", err)
	}

	// Initialize decoder
	d := NewDecoder()
	result, err := d.Init(data)
	if err != nil {
		t.Fatalf("Init failed: %v", err)
	}

	t.Logf("Initialized: %d Hz, %d channels", result.SampleRate, result.Channels)

	// Find reference data directory
	baseName := filepath.Base(testFile)
	baseName = baseName[:len(baseName)-4] // Remove .aac
	refDir := filepath.Join("/tmp", "faad2_ref_"+baseName)

	if _, err := os.Stat(refDir); os.IsNotExist(err) {
		t.Skipf("Reference data not found at %s. Run: ./scripts/check_faad2 %s", refDir, testFile)
	}

	// Decode frames and log progress
	// Full comparison will be enabled when decoding is complete
	offset := int(result.BytesRead)
	frameNum := 1
	maxFrames := 10 // Limit for initial testing

	for offset < len(data) && frameNum <= maxFrames {
		_, info, err := d.Decode(data[offset:])
		if err != nil {
			t.Logf("Frame %d decode error: %v", frameNum, err)
			break
		}
		if info == nil {
			break
		}

		t.Logf("Frame %d: consumed %d bytes, %d samples",
			frameNum, info.BytesConsumed, info.Samples)

		offset += int(info.BytesConsumed)
		frameNum++
	}

	t.Logf("Processed %d frames", frameNum-1)
}
