// Package tables contains lookup tables for AAC decoding.
package tables

import "errors"

//go:generate go run generate_iq_table.go

// ErrIQTableOverflow indicates the quantized value exceeds table bounds.
var ErrIQTableOverflow = errors.New("tables: inverse quantization value out of range")

// IQTableSize is the number of entries in the inverse quantization table.
// Ported from: IQ_TABLE_SIZE in ~/dev/faad2/libfaad/iq_table.h:44
const IQTableSize = 8192

// IQTable contains precomputed values of i^(4/3) for i in 0..8191.
// Used for inverse quantization: spec[i] = sign(quant[i]) * IQTable[|quant[i]|]
//
// Ported from: iq_table in ~/dev/faad2/libfaad/iq_table.h:51
// Generated by: go generate ./internal/tables
var IQTable [IQTableSize]float64

// IQuant performs inverse quantization: returns sign(q) * |q|^(4/3).
// Uses the precomputed IQTable for efficiency.
//
// Returns error if |q| >= IQTableSize (8192).
//
// Ported from: iquant() in ~/dev/faad2/libfaad/specrec.c:430-497
func IQuant(q int16) (float64, error) {
	if q < 0 {
		if -q >= IQTableSize {
			return 0, ErrIQTableOverflow
		}
		return -IQTable[-q], nil
	}
	if q >= IQTableSize {
		return 0, ErrIQTableOverflow
	}
	return IQTable[q], nil
}
