// Package tables contains lookup tables for AAC decoding.
package tables

//go:generate go run generate_iq_table.go

// IQTableSize is the number of entries in the inverse quantization table.
// Ported from: IQ_TABLE_SIZE in ~/dev/faad2/libfaad/iq_table.h:44
const IQTableSize = 8192

// IQTable contains precomputed values of i^(4/3) for i in 0..8191.
// Used for inverse quantization: spec[i] = sign(quant[i]) * IQTable[|quant[i]|]
//
// Ported from: iq_table in ~/dev/faad2/libfaad/iq_table.h:51
// Generated by: go generate ./internal/tables
var IQTable [IQTableSize]float64
