// Package tables contains lookup tables for AAC decoding.
package tables

import "errors"

//go:generate go run generate_iq_table.go

// ErrIQTableOverflow indicates the quantized value exceeds table bounds.
var ErrIQTableOverflow = errors.New("tables: inverse quantization value out of range")

// IQTableSize is the number of entries in the inverse quantization table.
// Ported from: IQ_TABLE_SIZE in ~/dev/faad2/libfaad/iq_table.h:44
const IQTableSize = 8192

// IQTable contains precomputed values of i^(4/3) for i in 0..8191.
// Used for inverse quantization: spec[i] = sign(quant[i]) * IQTable[|quant[i]|]
//
// Ported from: iq_table in ~/dev/faad2/libfaad/iq_table.h:51
// Generated by: go generate ./internal/tables
var IQTable [IQTableSize]float64

// Pow2SFTable contains precomputed 2^((i-25)/4) values for scale factor application.
// Index 25 = 1.0, smaller indices give smaller values, larger give larger values.
//
// Used for: spec[i] *= Pow2SFTable[sf + offset]
//
// Ported from: pow2sf_tab in ~/dev/faad2/libfaad/specrec.c:501-523
var Pow2SFTable = [64]float64{
	2.9802322387695313e-008, 5.9604644775390625e-008, 1.1920928955078125e-007,
	2.384185791015625e-007, 4.76837158203125e-007, 9.5367431640625e-007,
	1.9073486328125e-006, 3.814697265625e-006, 7.62939453125e-006,
	1.52587890625e-005, 3.0517578125e-005, 6.103515625e-005,
	0.0001220703125, 0.000244140625, 0.00048828125,
	0.0009765625, 0.001953125, 0.00390625,
	0.0078125, 0.015625, 0.03125,
	0.0625, 0.125, 0.25,
	0.5, 1.0, 2.0,
	4.0, 8.0, 16.0, 32.0,
	64.0, 128.0, 256.0,
	512.0, 1024.0, 2048.0,
	4096.0, 8192.0, 16384.0,
	32768.0, 65536.0, 131072.0,
	262144.0, 524288.0, 1048576.0,
	2097152.0, 4194304.0, 8388608.0,
	16777216.0, 33554432.0, 67108864.0,
	134217728.0, 268435456.0, 536870912.0,
	1073741824.0, 2147483648.0, 4294967296.0,
	8589934592.0, 17179869184.0, 34359738368.0,
	68719476736.0, 137438953472.0, 274877906944.0,
}

// Pow2FracTable contains 2^(i/4) for i in {0,1,2,3}.
// Used for fractional part of scale factor exponent.
//
// Ported from: pow2_table in ~/dev/faad2/libfaad/specrec.c:553-559
var Pow2FracTable = [4]float64{
	1.0,                               // 2^0
	1.1892071150027210667174999705605, // 2^0.25
	1.4142135623730950488016887242097, // 2^0.5
	1.6817928305074290860622509524664, // 2^0.75
}

// IQuant performs inverse quantization: returns sign(q) * |q|^(4/3).
// Uses the precomputed IQTable for efficiency.
//
// Returns error if |q| >= IQTableSize (8192).
//
// Ported from: iquant() in ~/dev/faad2/libfaad/specrec.c:430-497
func IQuant(q int16) (float64, error) {
	if q < 0 {
		if -q >= IQTableSize {
			return 0, ErrIQTableOverflow
		}
		return -IQTable[-q], nil
	}
	if q >= IQTableSize {
		return 0, ErrIQTableOverflow
	}
	return IQTable[q], nil
}
