// Copyright 2024 The go-aac Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package syntax

import (
	"os"
	"testing"
)

// TestParseCPE_FAAD2Reference tests CPE parsing against FAAD2 reference data.
// This test will be expanded once we have real stereo AAC test files and
// FAAD2 reference data generated by scripts/check_faad2.
//
// Test methodology:
//  1. Generate stereo AAC file: ffmpeg -f lavfi -i "sine=frequency=440:duration=1" \
//     -ac 2 -c:a aac -b:a 128k testdata/stereo.aac
//  2. Generate reference: ./scripts/check_faad2 testdata/stereo.aac
//  3. Compare parsed CPE fields against reference data
func TestParseCPE_FAAD2Reference(t *testing.T) {
	// Skip if no reference data available
	refDir := os.Getenv("FAAD2_REF_DIR")
	if refDir == "" {
		t.Skip("FAAD2_REF_DIR not set - skipping reference comparison")
	}

	// TODO: Implement detailed FAAD2 comparison
	// 1. Load stereo AAC test file
	// 2. Parse ADTS header to get configuration
	// 3. Parse CPE and compare against FAAD2 reference:
	//    - Compare element_instance_tag
	//    - Compare common_window flag
	//    - Compare ms_mask_present
	//    - Compare parsed ICS1 and ICS2 fields
	//    - Compare spectral data
	//
	// Test files to use:
	// - testdata/generated/aac_lc/44100_16_stereo_128k/*.aac
	//
	// Reference generation:
	// ./scripts/check_faad2 testdata/stereo.aac
	// Reference data in: /tmp/faad2_ref_stereo/

	_ = refDir // silence unused variable warning
	t.Skip("TODO: Implement FAAD2 reference comparison for CPE")
}

// TestParseCPE_StereoFile tests CPE parsing with a real stereo AAC file.
func TestParseCPE_StereoFile(t *testing.T) {
	t.Skip("TODO: Add integration test with real stereo AAC file")

	// Placeholder for future integration tests:
	// 1. Read stereo AAC file
	// 2. Skip ADTS header
	// 3. Parse raw_data_block to find CPE
	// 4. Verify CPE parsing succeeds
	// 5. Verify spectral data is populated for both channels
}
