//go:build ignore

// generate_mdct_tables.go generates MDCT twiddle factor tables.
// Run with: go run scripts/generate_mdct_tables.go > internal/mdct/tables.go
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println("// Code generated by generate_mdct_tables.go. DO NOT EDIT.")
	fmt.Println("//")
	fmt.Println("// These tables contain the pre/post twiddle factors for MDCT.")
	fmt.Println("// Formula: sincos[k] = sqrt(2/N) * exp(j * 2*PI * (k + 1/8) / N)")
	fmt.Println("//")
	fmt.Println("// Ported from: ~/dev/faad2/libfaad/mdct_tab.h (floating point section)")
	fmt.Println("")
	fmt.Println("package mdct")
	fmt.Println("")
	fmt.Println("import \"github.com/llehouerou/go-aac/internal/fft\"")
	fmt.Println("")

	// Generate tables for AAC sizes
	sizes := []int{2048, 256}

	for _, n := range sizes {
		generateTable(n)
	}
}

func generateTable(n int) {
	n4 := n / 4
	// FAAD2 floating point uses sqrt(2/N) as the scale factor
	scale := math.Sqrt(2.0 / float64(n))

	fmt.Printf("// mdctTab%d contains %d complex twiddle factors for N=%d MDCT.\n", n, n4, n)
	fmt.Printf("var mdctTab%d = [%d]fft.Complex{\n", n, n4)

	for k := 0; k < n4; k++ {
		// sincos[k] = sqrt(2/N) * exp(j * 2*PI * (k + 1/8) / N)
		angle := 2.0 * math.Pi * (float64(k) + 0.125) / float64(n)
		re := scale * math.Cos(angle)
		im := scale * math.Sin(angle)

		fmt.Printf("\t{Re: %.15e, Im: %.15e},\n", re, im)
	}

	fmt.Println("}")
	fmt.Println("")
}
