//go:build ignore

// generate_windows.go extracts window tables from FAAD2 header files.
// This ensures bit-exact matching with the reference implementation.
//
// Run with: go run scripts/generate_windows.go
package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
)

const (
	faad2SineWin = "/home/laurent/dev/faad2/libfaad/sine_win.h"
	faad2KBDWin  = "/home/laurent/dev/faad2/libfaad/kbd_win.h"
)

// windowTable holds extracted window data
type windowTable struct {
	name   string
	goName string
	size   int
	values []string
}

func main() {
	// Extract sine windows from sine_win.h
	sineTables := []windowTable{
		{name: "sine_long_1024", goName: "sineLong1024", size: 1024},
		{name: "sine_short_128", goName: "sineShort128", size: 128},
	}

	for i := range sineTables {
		values, err := extractTable(faad2SineWin, sineTables[i].name)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error extracting %s: %v\n", sineTables[i].name, err)
			os.Exit(1)
		}
		if len(values) != sineTables[i].size {
			fmt.Fprintf(os.Stderr, "%s: got %d values, want %d\n", sineTables[i].name, len(values), sineTables[i].size)
			os.Exit(1)
		}
		sineTables[i].values = values
	}

	// Generate window_sine.go
	if err := generateSineFile(sineTables); err != nil {
		fmt.Fprintf(os.Stderr, "error generating sine file: %v\n", err)
		os.Exit(1)
	}

	// Extract KBD windows from kbd_win.h
	kbdTables := []windowTable{
		{name: "kbd_long_1024", goName: "kbdLong1024", size: 1024},
		{name: "kbd_short_128", goName: "kbdShort128", size: 128},
	}

	for i := range kbdTables {
		values, err := extractTable(faad2KBDWin, kbdTables[i].name)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error extracting %s: %v\n", kbdTables[i].name, err)
			os.Exit(1)
		}
		if len(values) != kbdTables[i].size {
			fmt.Fprintf(os.Stderr, "%s: got %d values, want %d\n", kbdTables[i].name, len(values), kbdTables[i].size)
			os.Exit(1)
		}
		kbdTables[i].values = values
	}

	// Generate window_kbd.go
	if err := generateKBDFile(kbdTables); err != nil {
		fmt.Fprintf(os.Stderr, "error generating KBD file: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Generated internal/filterbank/window_sine.go")
	fmt.Println("Generated internal/filterbank/window_kbd.go")
}

// extractTable extracts a window table from a FAAD2 header file
func extractTable(filename, tableName string) ([]string, error) {
	file, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	var values []string
	scanner := bufio.NewScanner(file)

	// Match FRAC_CONST(value) pattern
	fracRegex := regexp.MustCompile(`FRAC_CONST\(([^)]+)\)`)

	inTable := false
	for scanner.Scan() {
		line := scanner.Text()

		// Detect start of table
		if strings.Contains(line, tableName+"[]") || strings.Contains(line, tableName+" []") {
			inTable = true
			continue
		}

		// Detect end of table
		if inTable && strings.Contains(line, "};") {
			break
		}

		if !inTable {
			continue
		}

		// Extract values from FRAC_CONST macros
		matches := fracRegex.FindAllStringSubmatch(line, -1)
		for _, m := range matches {
			if len(m) > 1 {
				// Validate it's a valid number
				_, err := strconv.ParseFloat(m[1], 64)
				if err == nil {
					values = append(values, m[1])
				}
			}
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return values, nil
}

func generateSineFile(tables []windowTable) error {
	f, err := os.Create("internal/filterbank/window_sine.go")
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by generate_windows.go; DO NOT EDIT.")
	fmt.Fprintln(f, "//")
	fmt.Fprintln(f, "// Sine window tables for IMDCT windowing.")
	fmt.Fprintln(f, "// Values extracted directly from ~/dev/faad2/libfaad/sine_win.h")
	fmt.Fprintln(f, "// to ensure bit-exact matching with FAAD2.")
	fmt.Fprintln(f, "//")
	fmt.Fprintln(f, "// Formula: w[n] = sin((π/N) * (n + 0.5)) for n = 0..N-1")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "package filterbank")
	fmt.Fprintln(f, "")

	for _, t := range tables {
		fmt.Fprintf(f, "// %s contains %d sine window coefficients.\n", t.goName, t.size)
		fmt.Fprintf(f, "var %s = [%d]float32{\n", t.goName, t.size)

		for i, v := range t.values {
			if i%4 == 0 {
				fmt.Fprint(f, "\t")
			}
			fmt.Fprintf(f, "%s, ", v)
			if i%4 == 3 {
				fmt.Fprintln(f)
			}
		}
		if len(t.values)%4 != 0 {
			fmt.Fprintln(f)
		}
		fmt.Fprintln(f, "}")
		fmt.Fprintln(f, "")
	}

	return nil
}

func generateKBDFile(tables []windowTable) error {
	f, err := os.Create("internal/filterbank/window_kbd.go")
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by generate_windows.go; DO NOT EDIT.")
	fmt.Fprintln(f, "//")
	fmt.Fprintln(f, "// Kaiser-Bessel Derived (KBD) window tables for IMDCT windowing.")
	fmt.Fprintln(f, "// Values extracted directly from ~/dev/faad2/libfaad/kbd_win.h")
	fmt.Fprintln(f, "// to ensure bit-exact matching with FAAD2.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "package filterbank")
	fmt.Fprintln(f, "")

	for _, t := range tables {
		fmt.Fprintf(f, "// %s contains %d KBD window coefficients.\n", t.goName, t.size)
		fmt.Fprintf(f, "var %s = [%d]float32{\n", t.goName, t.size)

		for i, v := range t.values {
			if i%4 == 0 {
				fmt.Fprint(f, "\t")
			}
			fmt.Fprintf(f, "%s, ", v)
			if i%4 == 3 {
				fmt.Fprintln(f)
			}
		}
		if len(t.values)%4 != 0 {
			fmt.Fprintln(f)
		}
		fmt.Fprintln(f, "}")
		fmt.Fprintln(f, "")
	}

	return nil
}
